### PR TITLE
Add ruby-3.4 native gem

### LINKED ISSUE #1132: Request for Platform-Specific Extensions for Ruby 3.4
Hello,

currently, platform-specific gems target `>= 2.5, < 3.4.dev`

Could platform-specific extensions be provided for Ruby 3.4?

### PR DESCRIPTION
**Pull request by larskanis**
Fixes #1132

### CODE REVIEW

**Comment by tagliala** [comment]
Failures are a consequence of ruby/setup-ruby#680

**Comment by chadlwilson** [comment]
Any chance of a release with these delicious new native gems for 3.4? 😅

**Comment by tagliala** [comment]
> Any chance of a release with these delicious new native gems for 3.4?

They have been released as 1.17.1

Refs:
- https://rubygems.org/gems/ffi/versions
- Example: https://rubygems.org/gems/ffi/versions/1.17.1-x86-linux-gnu

**Comment by chadlwilson** [comment]
Ahh, my bad, sorry! Was looking for a tag/changelog in the repo but seems the release wasn't tagged/changeloged.

**Comment by tagliala** [comment]
Oh, I see, I usually open a new request in that case. I'll do that

**Pull request merged**
