### PR TITLE
RBS for key modules and classes (mainly user-facing ones)

### PR DESCRIPTION
**Pull request by ParadoxV5**
A step towards #1039.

Written against [v1.16.3 docs](https://rubydoc.info/gems/ffi/1.16.3/FFI). Maintainers’ assistance needed to cover undocumented C-implemented APIs.

Blockers regarding the new dependency `rbs ~> 3.0`:
* It is incompatible with EOL Ruby version 2.5 which FFI gem still supports.
* JRuby does not support RBS.

Both of which can be worked around by not declaring the not-so-dependent `rbs ~> 3.0`.
But that’s like writing Yardocs without declaring Yardoc as a dep.

#### This PR

* FFI (top-level)
* AbstractMemory
  * Buffer
  * Pointer
    * AutoPointer
    * Function
    * MemoryPointer
* DataConverter
* Enum
  * Bitmask
* Enums
* Library
* NativeType
* Struct
  * ManagedStruct
  * Union
* StructByReference
* Type
  * ArrayType
  * FunctionType
  * StructByValue
* VariadicInvoker

<details><summary>

#### What still needs to be done

</summary>

* ConstGenerator
* DynamicLibrary
* Generator
* IO
* LastError
* LibraryPath
* NotFoundError
* NullPointerError
* Platform
* PlatformError
* StrPtrConverter
* StructGenerator
* StructLayout
* StructLayoutBuilder
* TypesGenerator

and also, perhaps, tests (with [RBS](https://github.com/ruby/rbs/blob/master/docs/sigs.md#testing-signatures) or [Steep](https://github.com/soutaro/steep))

</details>

### CODE REVIEW

**Comment by ParadoxV5** [comment]
[`Pointer#autorelease=`](https://rubydoc.info/gems/ffi/1.16.3/FFI/Pointer#autorelease=-instance_method) checks whether the argument is `true` or not. This means every truthy value except `true` is actually equivalent to `false` here. It should respect Ruby’s truthiness with `RTEST`.

**Comment by larskanis** [comment]
@ParadoxV5 Thank you very much for all your work!

What do you think about merging this? Having an incomplete RBS API definition is at least a good starting point. Or can it be a problem in the future to release something incomplete?

**Comment by ParadoxV5** [comment]
@larskanis 👋

> What do you think about merging this?

I was planning to do some more user-facing classes. I’ve been away over December focusing on [Advent of Code 2023](https://adventofcode.com/2023).

> Having an incomplete RBS API definition is at least a good starting point. Or can it be a problem in the future to release something incomplete?

Stubs should be forward-compatible.

---

A reminder that the CI fails because RBS 3.x is incompatible with Ruby 2.5 (which was EOL since a couple of years ago). RBS will have to downgrade if there’re no plans to raise the minimum Ruby version.

**Comment by ParadoxV5** [comment]
For consistency, custom typedefs should also be a `{Symbol => Type}` hashmap, no `String`s. But
https://github.com/ffi/ffi/blob/1403e20b4877ff2ffd4d2b0425c7c43ed2a2c25c/ext/ffi_c/Type.c#L281

**Comment by ParadoxV5** [comment]
Happy New Year @larskanis! This is all the class/method I’ll include for the first batch. Let me know if you prefer my commits squashed.

**Comment by larskanis** [comment]
There was some additional discussion in https://github.com/ParadoxV5/ruby-ffi/pull/1 . These changes are now included in this PR.

It mainly adds the ability to check the RBS files against the FFI test suite. It works by the following command line:
```
RBS_TEST_TARGET='FFI::*' RUBYOPT='-rrbs/test/setup'  bundle exec rake spec
```

**Pull request merged**
