### PR TITLE
Drop Ruby 1.8.7 support

### PR DESCRIPTION
**Pull request by koic**
[It seems that Ruby FFI does not support Ruby 1.8.7 and earlier.](https://github.com/ffi/ffi/pull/479/files)

I propose that required ruby version will be specified to `gemspec` file.

Thanks.

### CODE REVIEW

**Comment by tduehr** [comment]
There's a bit more to it than just updating the gemspec. We'll also want to remove code that handles 1.8.x specifically. Like that which caused #479.

**Comment by koic** [comment]
Thank you for your explanation.
Would you like me to close this issue?

**Comment by tduehr** [comment]
No, leave it open... If you can add to it, do so. Otherwise I'll continue from here at some point...

**Comment by koic** [comment]
I see. I removed code that handles 1.8.x specifically in [this commit](https://github.com/koic/ffi/commit/d18a5fcfb890b5b68d215377c50cd8608ba53d43).
Would you be willing to confirm the codes?

**Pull request merged**
