### PR TITLE
Update embedded libffi to 3.2.1

### PR DESCRIPTION
**Pull request by kaustubh-d**
Update embedded libffi to 3.2.1 so that gem can be successfully built and installed on ppc64le.

This version of libffi adds support for PowerPC 64 Little and Big Endian archs. See #413

### CODE REVIEW

**Comment by tduehr** [comment]
There's a bit more to upgrading libffi than just copying it in... I'll have a branch w/ it updated for some additional testing in a bit.

**Comment by tduehr** [comment]
@djberg96 Can you test the libffi-3.2.1 branch on windows?

**Comment by djberg96** [comment]
@tduehr I'm still having this issue: https://github.com/ffi/ffi/issues/201

**Comment by kaustubh-d** [comment]
@tduehr - no problem! realized that when trying on new system. One issue I see is the extension build should trigger the internal libffi configure and then use the generated ffi.h to set the extension build flags (extconf.h) from here https://github.com/ffi/ffi/blob/master/ext/ffi_c/extconf.rb#L28-L31.

**Pull request closed without merging**
