### PR TITLE
Add types.conf of Apple silicon mac

### PR DESCRIPTION
**Pull request by Watson1978**
I just run following command on Apple silicon Mac

```
$ system_profiler SPHardwareDataType
Hardware:

    Hardware Overview:

      Model Name: Apple Development Platform
      Model Identifier: ADP3,2
      Processor Name: Apple A12Z Bionic
      Number of CPUs: 8
      L2 Cache (per CPU): 8 MB
      Memory: 16 GB
      Serial Number (system): C07CR95UPYPQ
      Hardware UUID: 39211857-BD84-57C6-B060-DEBF788CC50F
      Activation Lock Status: Disabled

$ rake types_conf

```

Related to https://github.com/ffi/ffi/issues/800

Thanks

### CODE REVIEW

**Comment by larskanis** [comment]
Thank you for providing the type list on this new platform! I think the architecture and the path should be called "aarch64" instead of "arm". I opened #802 to fix this. If you agree, could you please verify that the `rake types_conf` generates the file in `aarch64-darwin/types.conf`?

**Comment by Watson1978** [comment]
I tried #802, however, it still generate `arm-darwin` directory.

```
[pr/802][~/prj/ffi]$ rake types_conf
[pr/802][~/prj/ffi]$ git status
On branch pr/802
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        lib/ffi/platform/arm-darwin/

nothing added to commit but untracked files present (use "git add" to track)
```

Seems that `RbConfig::CONFIG['host_cpu']` has `arm` value.
https://gist.github.com/Watson1978/16c3f8b2673a8db266b2332b73cb1bc9

I'm wondering whether it's a Ruby problem

**Comment by Watson1978** [comment]
I'm confirming this behavior in https://bugs.ruby-lang.org/issues/17021

**Comment by headius** [comment]
What is the status of this? As I am sure @larskanis knows, JRuby's FFI layer also depends on libffi, and we are eagerly awaiting a usable build.

**Comment by larskanis** [comment]
This is more or less blocked by https://bugs.ruby-lang.org/issues/17021 . We could however add a workaround until the RbConfig variables are fixed.

**Comment by eregon** [comment]
I'd recommend to workaround for now, and assume any `^arm` on `darwin` is `aarch64`.
It would be good to fix the bug upstream, but even if it is fixed it won't be applied to existing Ruby releases.

**Comment by eregon** [comment]
@larskanis The bug was fixed upstream.
Nobu recommends to use `target_cpu`: https://bugs.ruby-lang.org/issues/17021#note-8
I think we should try that.

**Comment by larskanis** [comment]
I tried using `target_cpu` instead of `host_cpu` in [this branch](https://github.com/larskanis/ffi/tree/arm-darwin). However I'm uncertain if it breaks too much. For instance:

  * 32 bit Mingw uses "target_cpu"=>"i386" and "host_cpu"=>"i686"
  * 64 bit Minwg uses "target_cpu"=>"x64" and "host_cpu"=>"x86_64"

While `i386` vs. `i686` is properly handled in [platform.rb](https://github.com/ffi/ffi/blob/187328eb3c9e3088e2e3704e7ca68ae9928dee44/lib/ffi/platform.rb#L66), the term `x64` is not recognized.

I posted https://github.com/ffi/ffi/pull/843 which still uses `host_cpu` but adds a workaround for MacOS.

**Comment by eregon** [comment]
Agreed, I remember also using `target_os` sometimes gives different values.

BTW, that Regexp `/i?86|x86|i86pc/` seems buggy, it should probably be `/i\d?86|x86|i86pc/`

**Pull request closed without merging**
