### PR TITLE
Make FFI work on heroku cedar-14

### PR DESCRIPTION
**Pull request by glitch003**
This small change adds a search path to the library lookup logic.  It specifically adds the "/lib/x86_64-linux-gnu/" path which is where libraries live on heroku cedar-14.

This change keeps backwards compatibility with the existing search paths that were already present :)

### CODE REVIEW

**Comment by trostli** [comment]
nice. i just ran into this issue myself

**Comment by trostli** [comment]
Actually the other place where libraries live on Heroku is `/app/vendor`. Can you add that path too? That is where they are installed when using buildpacks

**Comment by glitch003** [comment]
@trostli sure, done

**Comment by trostli** [comment]
Thanks!

**Comment by tduehr** [comment]
That needs to be created specific to the platform currently being used rather than being hard coded to x86.

**Comment by danielpclark** [comment]
Shouldn't a server environment use values provided by ENV?  This would allow any server or system to provide proper configurations which is easy enough to document.

```ruby
# # Example
# ENV['FFI_LIBS'] = "/app/vendor/;/lib/x86_64-linux-gnu/"
path = ['/usr/lib/','/usr/local/lib/']
path += ENV['FFI_LIBS'].to_s.split(/[;,]/)
# # Path is now
# ['/usr/lib/', '/usr/local/lib/', '/app/vendor/', '/lib/x86_64-linux-gnu/']
path.find do |pth|
  File.exist?(pth + libname)
end
```

**Comment by trostli** [comment]
good suggestion @danielpclark

**Comment by gsdean** [comment]
is this getting merged?

**Comment by headius** [comment]
@gsdean I see @tduehr comment above but no follow-up commits, so I'm not sure if this is ready or not.

**Comment by larskanis** [comment]
There is another PR which modifies the search path logic: #616 . To be honest, I would rather remove these hardcoded paths than adding random new ones.

**Comment by tduehr** [comment]
Please rebase this if it's still an issue.

**Comment by dmtask** [comment]
When will this be finished?

**Comment by larskanis** [comment]
This will not be merged. We'll not add architecture specific paths that are wrong on all other architectures.

FFI is not responsible for fixing misconfigurations in the library setup. FFI respects the library paths that the operating system provides. This is /etc/ld.conf and LD_LIBRARY_PATH for instance on Linux.

To the contrary we'll remove the static paths entirely in a future release or limit then to operating systems that really need them.

**Pull request closed without merging**
