### PR TITLE
Remove redundant CI jobs

### PR DESCRIPTION
**Pull request by eregon**
See https://github.com/ffi/ffi/issues/760#issuecomment-605897217

We should be able to move the remaining jobs to GitHub Actions as well, but might as well cleanup the redundant ones now.

### CODE REVIEW

**Comment by eregon** [comment]
I filed an issue to Bundler regarding the transient failure on macOS on Ruby 2.3: https://github.com/rubygems/rubygems/issues/3463

**Comment by larskanis** [comment]
Travis-CI did a good job for a decade by now. So I wouldn't delete the jobs immediately. We can do this when Github Actions worked well with FFI for a while or when we're tired to update Travis. But thank you for your efforts!

**Comment by larskanis** [comment]
Technically this PR looks good.

**Comment by eregon** [comment]
OK, no problem to wait.

**Comment by eregon** [comment]
Let's close this since we don't plan to merge it soon, we can always reopen it.

**Comment by eregon** [comment]
@larskanis Should we merge this now?

TravisCI is pretty slow, [fails randomly](https://travis-ci.org/github/ffi/ffi/builds) and causes essentially duplicated testing.

**Comment by larskanis** [comment]
I'm fine with removing these jobs.

**Comment by eregon** [comment]
Great, I'll merge then :)

**Pull request merged**
