### PR TITLE
Rename sparc64-linux -> sparcv9-linux

### PR DESCRIPTION
**Pull request by matoro**
In https://github.com/ffi/ffi/pull/575, 64-bit sparc was changed to also
use sparcv9 as the platform name, but the types.conf directory was never
renamed.  This breaks only on Ruby 3.0 and later due to the fileutils
change to use keyword arguments in
https://github.com/ruby/fileutils/commit/482de6d397742526d1111576e2791f9b7051e3c0

### CODE REVIEW

**Comment by larskanis** [comment]
The file rename make sense, but how is it related to fileutils and the
change to use keyword arguments?

**Comment by matoro** [comment]
> The file rename make sense, but how is it related to fileutils and the change to use keyword arguments?

Throws an ArgumentError in the arguments to mkdir_p.  Our downstream bug report is here:  https://bugs.gentoo.org/847286

Traceback with `rake --trace`:
```
** Invoke default (first_time)
** Invoke /var/tmp/portage/dev-ruby/ffi-1.15.5/work/ruby31/ffi-1.15.5/lib/ffi/platform/sparcv9-linux/types.conf (first_time)
** Execute /var/tmp/portage/dev-ruby/ffi-1.15.5/work/ruby31/ffi-1.15.5/lib/ffi/platform/sparcv9-linux/types.conf
rake aborted!
ArgumentError: wrong number of arguments (given 2, expected 1)
/usr/lib64/ruby/3.1.0/fileutils.rb:206:in `mkdir_p'
/var/tmp/portage/dev-ruby/ffi-1.15.5/work/ruby31/ffi-1.15.5/gen/Rakefile:12:in `block in <top (required)>'
/usr/lib64/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/usr/lib64/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/usr/lib64/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/usr/lib64/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/lib64/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/usr/lib64/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/lib64/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/usr/lib64/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/usr/lib64/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/usr/lib64/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/usr/lib64/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/usr/lib64/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/lib64/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/usr/lib64/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/usr/lib64/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/lib64/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/usr/lib64/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/usr/lib64/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/usr/lib64/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/usr/lib64/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/usr/lib64/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/lib64/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/usr/lib64/ruby/gems/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/bin/rake:9:in `load'
/usr/bin/rake:9:in `<main>'
Tasks: TOP => default => /var/tmp/portage/dev-ruby/ffi-1.15.5/work/ruby31/ffi-1.15.5/lib/ffi/platform/sparcv9-linux/types.conf
```

**Comment by matoro** [comment]
Unfortunately there seems to be one more hurdle to getting this working, the callback tests are failing:

```
Failures:

  1) Callback interop from ffi to ffi
     Failure/Error: LibTestFFI.testCallbackVrV(FFI::Pointer.new(func.to_i))
     
     RangeError:
       bignum too big to convert into `long long'
     # ./spec/ffi/callback_spec.rb:883:in `initialize'
     # ./spec/ffi/callback_spec.rb:883:in `new'
     # ./spec/ffi/callback_spec.rb:883:in `block (3 levels) in <module:CallbackInteropSpecs>'
     # ./spec/ffi/callback_spec.rb:872:in `assert_callback_in_same_thread_called_once'
     # ./spec/ffi/callback_spec.rb:881:in `block (2 levels) in <module:CallbackInteropSpecs>'

  2) Callback interop from ffi to ffi with blocking:true
     Failure/Error: LibTestFFI.testCallbackVrV_blocking(FFI::Pointer.new(func.to_i))
     
     RangeError:
       bignum too big to convert into `long long'
     # ./spec/ffi/callback_spec.rb:890:in `initialize'
     # ./spec/ffi/callback_spec.rb:890:in `new'
     # ./spec/ffi/callback_spec.rb:890:in `block (3 levels) in <module:CallbackInteropSpecs>'
     # ./spec/ffi/callback_spec.rb:872:in `assert_callback_in_same_thread_called_once'
     # ./spec/ffi/callback_spec.rb:888:in `block (2 levels) in <module:CallbackInteropSpecs>'

Finished in 6.9 seconds (files took 18.85 seconds to load)
4944 examples, 2 failures

Failed examples:

rspec ./spec/ffi/callback_spec.rb:880 # Callback interop from ffi to ffi
rspec ./spec/ffi/callback_spec.rb:887 # Callback interop from ffi to ffi with blocking:true
```

I dug in and added a `p func` right before the assert line, and it prints:

```
#<FFI::Function address=0xfff80001000d4000 size=48>
```

This makes no sense, as that address is indeed out of the 64-bit range.

**Comment by larskanis** [comment]
I think #962 should fix the "bignum too big to convert into `long long'" issue.

**Comment by matoro** [comment]
> I think #962 should fix the "bignum too big to convert into `long long'" issue.

Yes, it does!  Everything passes now, thank you so much!

**Pull request merged**
