### PR TITLE
Update types for FreeBSD 12

### PR DESCRIPTION
**Pull request by adam12**
The types for time_t and suseconds_t should be long and not int.

Complementary of 4ba53c5

Related to #544 and #627

### CODE REVIEW

**Comment by larskanis** [comment]
Could you please update ffi to latest changes on master, run `rake types_conf` and send a pull request for the resulting changes? It should update the types based on system header files for platform `x86_64-freebsd12`.

**Comment by adam12** [comment]
I've opened #722 with the generated types. I had to install and use `gcc`. I'm not sure if there will be any drawbacks from that.

I did notice a bunch of new types have been added to the list of types. Let me know if there is anything else required.

**Comment by larskanis** [comment]
This is fixed in libpq and will be part of PostgreSQL-12.1: https://github.com/postgres/postgres/commit/ba19a6b73c5bd771d8864171ede03503a9ff564e

**Comment by larskanis** [comment]
Thanks @adam12 , I merged #722 . I'm curious why clang doesn't work, but I think gcc headers are OK as well.

**Comment by adam12** [comment]
> Thanks @adam12 , I merged #722 . I'm curious why clang doesn't work, but I think gcc headers are OK as well.

Thanks for merging!

**Pull request closed without merging**
