### PR TITLE
Configure AppVeyor CI

### PR DESCRIPTION
**Pull request by MikaelSmith**
Adds a build script for AppVeyor, issue #444.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
The build failed, at https://ci.appveyor.com/project/MikaelSmith/ffi/build/1.0.1. I'm not really sure how to setup the ffi build environment on Windows. Apparently running rake test with Ruby DevKit setup on Windows isn't sufficient...

**Comment by tduehr** [comment]
I'm not sure this is an FFI problem, it's timing out at 40minutes. Did you rerun them again with the same result?

**Comment by larskanis** [comment]
This was on my agenda already for some time. I'll open a pull request with
a working appveyor setup and several fixes in the test suite.

**Comment by MikaelSmith** [comment]
https://ci.appveyor.com/project/MikaelSmith/ffi/build/1.0.2 might be a better example. Not sure why the timeouts on Bundler are happening. Errors like https://ci.appveyor.com/project/MikaelSmith/ffi/build/1.0.1/job/t43o01yyee2xulx0 are what I was unsure about.

**Comment by tduehr** [comment]
Thanks for the help on this guys.I'll take a poke at it when I get a chance to look at my windows VM as well.

**Comment by larskanis** [comment]
@MikaelSmith Based on you work, I have added some more fixes in #450 .

**Comment by MikaelSmith** [comment]
Thanks @larskanis, I wasn't sure where to start with the Windows build tasks. Closing in favor of #450.

**Pull request closed without merging**
