### PR TITLE
Make CI green

### PR DESCRIPTION
**Pull request by eregon**
On master two jobs are failing, and I don't see an easy way to fix them.

So until then, let's mark them as allow failures so we don't regress on other CI jobs, and the CI status is actually useful to evaluate PRs.

### CODE REVIEW

**Comment by eregon** [comment]
@larskanis Could you make both TravisCI and AppVeyor as required checks?
That way PRs don't look "green" before both CIs have run, which -- given TravisCI was not working recently -- was rather confusing.

**Comment by eregon** [comment]
TravisCI is running but somehow is not reported as a status on this PR: https://travis-ci.org/github/ffi/ffi

**Comment by eregon** [comment]
TravisCI is green now: https://travis-ci.org/github/ffi/ffi/builds/668074980
@larskanis Let's merge this?

**Comment by larskanis** [comment]
I fixed powerpc yesterday, the rest is fine for merge. I'll omit this one commit. Thank you!

**Comment by larskanis** [comment]
Merged manuely.

**Pull request closed without merging**
