### PR TITLE
add support for ruby 2.3.0 (2.2.0 was released Dec. 25th 2014,…

### PR DESCRIPTION
**Pull request by bestori**
… which is almost a year and a half before this commit).

### CODE REVIEW

**Comment by larskanis** [comment]
rake-compiler-dock must be updated to version 0.5.x to support ruby-2.3 cross builds.

**Comment by tduehr** [comment]
I'm not sure travis support 2.3 yet either.

**Comment by larskanis** [comment]
@tduehr Yes, travis needs "2.3.0" as version string.

**Comment by larskanis** [comment]
I'll prepare an updated PR addressing the mentioned issues.

**Comment by tduehr** [comment]
bump 2.2 and 2.1 as well, please.

**Comment by larskanis** [comment]
@tduehr What do you mean with bumping versions 2.2 and 2.1?

In case you're talking about `RUBY_CC_VERSION`, the versions can not easily changed, because they directly refer to the cross ruby versions of rake-compiler-dock. And I'll not change these versions because this would break other projects. Luckily there's no need to change the cross ruby versions, because [ABI compatiblity will not change within the same MINOR version](https://www.ruby-lang.org/de/news/2013/12/21/ruby-version-policy-changes-with-2-1-0/) . I'd update cross ruby versions only in case of such an ABI break. (Ideally rake-compiler would accept `RUBY_CC_VERSION=2.1:2.2:2.3`, but that's not the case for now.)

**Comment by tduehr** [comment]
I would expect rake-compiler-dock to have updated to the latest ruby installer versions. But, you're right, they'll still work for the current ones when compiled against the version in there.

**Comment by larskanis** [comment]
I've opened an updated PR in #495 , that passes all travis-ci versions. It also builds binary windows gems for RubyInstaller-2.3.

**Comment by bestori** [comment]
👍

**Pull request closed without merging**
