### PR TITLE
Fix multiple problems on FreeBSD

### PR DESCRIPTION
**Pull request by asomers**

### CODE REVIEW

**Comment by tduehr** [comment]
Does this apply to netbsd and openbsd as well?

**Comment by asomers** [comment]
I've only tested it on FreeBSD.  But my expectation would be that the Makefile change affects all of the BSDs, excluding OSX.  The compiler choice change should only affect FreeBSD and OSX.

**Comment by larskanis** [comment]
Is this PR still valid? Or are the issues on FreeBSD fixed with ffi-1.10.0?

**Comment by asomers** [comment]
I can't reproduce it now.

**Comment by asomers** [comment]
Closing stale PR.

**Pull request closed without merging**
