### PR TITLE
Fix PaX

### PR DESCRIPTION
**Pull request by forgottenswitch**
Drop `ClosurePool` in favor of PaX-compatible libffi functions.

```
Finished in 2.41 seconds (files took 11.4 seconds to load)
4845 examples, 0 failures
```

### CODE REVIEW

**Comment by forgottenswitch** [comment]
This still needs MPROTECT

**Comment by forgottenswitch** [comment]
Sorry, was in wrong `git worktree`. It does fix the ruby ffi requiring MPROTECT.

**Comment by forgottenswitch** [comment]
Verified with
```
gem uninstall ffi
gem build ffi.gemspec
gem install ./ffi-1.9.14
cd
jekyll new hello_jekyll
cd hello_jekyll
bundle exec jekyll serve
# It works on http://localhost:4000
```

**Comment by forgottenswitch** [comment]
Oops, fails on MacOS (due to USE_RAW removal?)

**Comment by forgottenswitch** [comment]
Travis needs `makeinfo` to be installed.

**Comment by forgottenswitch** [comment]
The build requires `makeinfo` package to be installed in travis.

**Comment by forgottenswitch** [comment]
It wouldn't `rake test` with stable libffi 3.2.1, but would on latest master.

**Comment by tduehr** [comment]
Thanks, I'll look at this and incorporate some of your changes into the libffi update branch and we'll see what's left after that.

**Comment by tduehr** [comment]
Can you rebase off the current master? Some of this may have been addressed from the ppc64le fixes.

**Comment by forgottenswitch** [comment]
Done.

Feel free to ignore this [and merge anyway], but PaX itself could be patched instead, as being overly-restrictive. Current (incomplete, but sufficient for the case) state:
- [PaX patch series](https://github.com/forgottenswitch/linux/tree/pax-2017.07.13)
- [userspace support](https://github.com/forgottenswitch/prctl_wx)

**Pull request merged**
